### ISSUE TITLE
Support latest Terragrunt

### ISSUE THREAD

**Issue by Vad1mo** [cytopia/docker-terragrunt#11]
it would be nice if latest Terragrunt was supported, v0.23.2. 
I could make a PR but it is not clear if only the ci file needed to be extended or more.

**Comment by cytopia** [comment]
@Vad1mo afaik the `latest` tag should always have the latest Terragrunt version. Did you do a `docker pull`?

**Comment by Vad1mo** [comment]
Didn't try latest, usually i prefer tagged version. but will give it a try

**Comment by cytopia** [comment]
You can derive from the table in the Readme which version is available in what Docker image tag: https://github.com/cytopia/docker-terragrunt#rolling-releases
