### ISSUE TITLE
latest doesn't contain Terraform 0.13.6

### ISSUE THREAD

**Issue by DaRolla** [cytopia/docker-terragrunt#21]
Hi there,

the latest Docker image contains Terraform 0.13.5.

But Terraform 0.13.6. was released on January: https://github.com/hashicorp/terraform/releases/tag/v0.13.6

Cheers,
DaRolla

**Comment by cytopia** [comment]
@DaRolla fixed in https://github.com/cytopia/docker-terragrunt/pull/22
